language: python

matrix:
  include:
    - os: linux
      env: INSTALL=true TESTFILE=./testing_one.py
      python: 2.7
    - os: linux
      env: INSTALL=true TESTFILE=./testing_two.py
      python: 2.7
    - os: linux
      env: INSTALL=true TESTFILE=./testing_three.py
      python: 2.7
    - os: linux
      env: INSTALL=false TESTFILE=./testing_six.py
      python: 2.7

install:
  - if [ ${INSTALL} = "true"]; then
    pip install pexpect ;
    pip install lxml ;
    pip install selenium==2.53.0 ;
    fi


script:
    - python $TESTFILE