language: python

matrix:
  include:
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_one.py
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_two.py
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_three.py
      python: 2.7
    - os: linux
      env: INSTALL=no TESTFILE=./testing_six.py
      python: 2.7

  -

script:
    - if [ ${INSTALL} == "yes"]; then pip install pexpect ; fi
    - python $TESTFILE