language: python

matrix:
  include:
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_one.py
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_two.py
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_three.py
      python: 2.7
    - os: linux
      env: INSTALL=no TESTFILE=./testing_six.py
      python: 2.7

install:
    - if [ ${INSTALL} = "yes" ]; then
        pip install pexpect ;
        pip install requests ;
        pip install lxml ;
        pip install selenium==2.53.0 ;
      fi

script:
    - python $TESTFILE