language: python

matrix:
  include:
    - os: linux
      env: INSTALL=no TESTFILE=./testing_one.py RELEASE=no PYLINT=yes
      python: 2.7

install:
    - if [ ${INSTALL} = "yes" ]; then
        pip install pexpect ;
        pip install requests ;
        pip install lxml ;
        pip install selenium==2.53.0 ;
      fi

script:
    - export BRANCH=$(if [ ${TRAVIS_PULL_REQUEST} = "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
    - echo "The branch being built is - $BRANCH"
    - if [ ${BRANCH} = "release" ] ; then
        python $TESTFILE ;
      else
        if [ ${BRANCH} != "release"  -a  ${RELEASE} = "no" ] ; then
          python $TESTFILE ;
        else
          echo $TESTFILE "will not run as this is not a release branch" ;
        fi
      fi
    - pip install pylint;
    - sudo apt-get install bc;
    - ./Tools/pylint_judge.sh;