language: python

matrix:
  include:
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_one.py RELEASE=no
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_two.py RELEASE=no
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_three.py RELEASE=no
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_four.py RELEASE=yes
      python: 2.7
    - os: linux
      env: INSTALL=yes TESTFILE=./testing_five.py RELEASE=yes
      python: 2.7
    - os: linux
      env: INSTALL=no TESTFILE=./testing_six.py RELEASE=no
      python: 2.7

install:
    - if [ ${INSTALL} = "yes" ]; then
        pip install pexpect ;
        pip install requests ;
        pip install lxml ;
        pip install selenium==2.53.0 ;
      fi

script:
    - if [ ${TRAVIS_BRANCH} = "release" ] ; then
        python $TESTFILE ;
      else
        if [ ${TRAVIS_BRANCH} != "release"  -a [ ${RELEASE} = "no" ] ; then
          python $TESTFILE ;
        else
          echo $TESTFILE "will not run as this is not a release branch" ;
        fi
      fi