language: python

matrix:
  include:
    - os: linux
      env: INSTALL=true
      python: 2.7
    - os: linux
      env: INSTALL=false
      python: 2.7

install:
  - if [[ "$INSTALL" == "true"]]; then pip install pexpect ; fi
  - if [[ "$INSTALL" == "true"]]; then pip install lxml ; fi
  - if [[ "$INSTALL" == "true"]]; then pip install selenium==2.53.0 ; fi

env:
  - TESTFILE=./testing_one.py
  - TESTFILE=./testing_two.py
  - TESTFILE=./testing_three.py
  - TESTFILE=./testing_four.py
  - TESTFILE=./testing_five.py
  - TESTCASE=./testing_six.py
  
script:
    - if [[ "$INSTALL" == "true"]]; then python $TESTFILE ; fi
    - if [[ "$INSTALL" == "false"]]; then python $TESTCASE ; fi