language: python

python:
  - 2.7


install:
  - pip install pexpect
  - pip install lxml
  - pip install selenium==2.53.0

env:
  - TESTFILE=./testing_one.py
  - TESTFILE=./testing_two.py
  - TESTFILE=./testing_three.py
  - TESTFILE=./testing_four.py
  - TESTFILE=./testing_six.py

script:
    - python $TESTFILE